### PR TITLE
217 notification error + NFT create Fix

### LINKED ISSUE #217: Check Notification Messages
Make sure they are consistent and make sense

### PR DESCRIPTION
**Pull request by WilliamJiH**
Screenshot 2022-12-05 at 7 57 58 PM
Screenshot 2022-12-05 at 7 58 43 PM

### CODE REVIEW

File: backend/src/utils/nftStorageUtils.js [hunk 1]
```diff
@@ -35,7 +35,12 @@ async function burn(url) {
...
 async function getImageUrl(metadataUrl) {
-    const res = await axios.get(metadataUrl);
-    return ipfsToHttps(res.data.image);
+    for (let i = 0; i < 10; i++) {
+        const res = await axios.get(metadataUrl);
+        if (res && res.data.image) {
+            return ipfsToHttps(res.data.image);
+        }
+    }
+    await new Promise((resolve) => setTimeout(resolve, 1000));
```
Comment (InfTkm) [inline backend/src/utils/nftStorageUtils.js]: move this to inside the for loop so that it waits between each try

**Review by InfTkm — CHANGES_REQUESTED** [review]

**Review by yuliwilliam — APPROVED** [review]
