### PR TITLE
Close Notification when Transaction Fails

### LINKED ISSUE #177: Close Notification when Transaction Fails

### PR DESCRIPTION
**Pull request by yuliwilliam**
close #177

### CODE REVIEW

File: infty/src/pages/NftPage.vue [hunk 1]
```diff
@@ -247,23 +247,40 @@ export default {
...
+                return;
+            }
             const data = {
                 nft_id: this.card.nft_id,
                 buyer: getters.getAddress,
                 commission: this.listing_commision,
                 commission_currency: "cfx",
             };
-            axios
+            await axios
```
Comment (InfTkm) [inline infty/src/pages/NftPage.vue:283]: 可以又。then 又await吗

Comment (yuliwilliam) [reply infty/src/pages/NftPage.vue:283]: yep, it doesn't really matter

**Review by InfTkm — APPROVED** [review]
